Ideas for data analysis:
* Total distance
* Total time
* Percentage of distance in each sport type
* Percentage of time in each sport type
* Number of activities per month over time
* Distance per month over time
* Time per month over time

In [1]:
import pandas as pd
import json

In [2]:
def read_datastore(file_name):
    try:
        with open(file_name, 'r') as file:
            return json.load(file)
    except FileNotFoundError:
        print(f'Error reading datastore: File not found: {file_name}')
        return None
    except json.JSONDecodeError:
        print(f'Error reading datastore: Invalid JSON format in file: {file_name}')
        return None

In [3]:
data = read_datastore('data.json')['data']
df = pd.DataFrame(data)
df

,resource_state,athlete,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,id,...,elev_high,elev_low,upload_id,upload_id_str,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,workout_type
0,2,"{'id': 120371207, 'resource_state': 1}",Walk 255,7317.5,4947,4947,0.0,Walk,Walk,14594978392,...,26.2,24.5,1.557380e+10,15573803917,shealth32d51d7a-c6f3-43a5-9334-7e6a85cfe868.tcx,False,0,0,False,NaN
1,2,"{'id': 120371207, 'resource_state': 1}",Walk 254,3339.4,2510,2551,0.0,Walk,Walk,14585120401,...,26.1,24.5,1.556320e+10,15563204229,shealth968e8234-524a-48e3-8398-ff1327425184.tcx,False,0,0,False,NaN
2,2,"{'id': 120371207, 'resource_state': 1}",Walk 253,3319.6,2313,2338,0.0,Walk,Walk,14573011717,...,26.2,24.5,1.555014e+10,15550138008,shealth855c9d09-6e6a-4981-b132-0b5311b2d220.tcx,False,0,0,False,NaN
3,2,"{'id': 120371207, 'resource_state': 1}",Run 279,5044.0,1773,1773,14.4,Run,Run,14568807302,...,26.6,22.0,1.554562e+10,15545624873,shealthbf20e46d-4ce5-4023-92e4-2a0bdb9e8422.tcx,False,0,0,False,3.0
4,2,"{'id': 120371207, 'resource_state': 1}",Warmup Run 279,884.9,387,393,0.0,Run,Run,14568515363,...,26.1,24.5,1.554531e+10,15545313403,shealth5ca420e2-4331-43ac-a465-d5464fc6aa9e.tcx,False,0,0,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1605,2,"{'id': 120371207, 'resource_state': 1}","Run 3/24, ST&F 2022",3910.7,1201,1201,20.1,Run,Run,11287810792,...,NaN,NaN,NaN,NaN,None,False,0,4,False,0.0
1606,2,"{'id': 120371207, 'resource_state': 1}","Run 10/19, XC 2021",6662.7,2213,2213,0.0,Run,Run,11287795809,...,NaN,NaN,NaN,NaN,None,False,0,3,False,0.0
1607,2,"{'id': 120371207, 'resource_state': 1}","Run 10/14, XC 2021",5841.9,1869,1869,0.0,Run,Run,11287786775,...,NaN,NaN,NaN,NaN,None,False,0,3,False,2.0
1608,2,"{'id': 120371207, 'resource_state': 1}","Run 10/13, XC 2021",6566.1,2100,2100,0.0,Run,Run,11287779715,...,NaN,NaN,NaN,NaN,None,False,0,3,False,2.0
1609,2,"{'id': 120371207, 'resource_state': 1}","Random Run, XC 2021",273.6,227,227,0.0,Run,Run,11287771867,...,NaN,NaN,NaN,NaN,None,False,0,3,False,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   resource_state                 1610 non-null   int64
 1   athlete                        1610 non-null   object
 2   name                           1610 non-null   object
 3   distance                       1610 non-null   float64
 4   moving_time                    1610 non-null   int64
 5   elapsed_time                   1610 non-null   int64
 6   total_elevation_gain           1610 non-null   float64
 7   type                           1610 non-null   object
 8   sport_type                     1610 non-null   object
 9   id                             1610 non-null   int64
 10  start_date                     1610 non-null   object
 11  start_date_local               1610 non-null   object
 12  timezone                       1610 non-null   object
 13  utc_offset                     1610 non-null   int64
 14  location_city                  0 non-null      object
 15  location_state                 0 non-null      object
 16  location_country               0 non-null      object
 17  achievement_count              1610 non-null   int64
 18  kudos_count                    1610 non-null   int64
 19  comment_count                  1610 non-null   int64
 20  athlete_count                  1610 non-null   int64
 21  photo_count                    1610 non-null   int64
 22  map                            1610 non-null   object
 23  trainer                        1610 non-null   bool
 24  commute                        1610 non-null   bool
 25  manual                         1610 non-null   bool
 26  private                        1610 non-null   bool
 27  visibility                     1610 non-null   object
 28  flagged                        1610 non-null   bool
 29  gear_id                        1435 non-null   object
 30  start_latlng                   1610 non-null   object
 31  end_latlng                     1610 non-null   object
 32  average_speed                  1610 non-null   float64
 33  max_speed                      1610 non-null   float64
 34  average_cadence                855 non-null    float64
 35  has_heartrate                  1610 non-null   bool
 36  average_heartrate              100 non-null    float64
 37  max_heartrate                  100 non-null    float64
 38  heartrate_opt_out              1610 non-null   bool
 39  display_hide_heartrate_option  1610 non-null   bool
 40  elev_high                      1363 non-null   float64
 41  elev_low                       1363 non-null   float64
 42  upload_id                      1363 non-null   float64
 43  upload_id_str                  1363 non-null   object
 44  external_id                    1363 non-null   object
 45  from_accepted_tag              1610 non-null   bool
 46  pr_count                       1610 non-null   int64
 47  total_photo_count              1610 non-null   int64
 48  has_kudoed                     1610 non-null   bool
 49  workout_type                   1199 non-null   float64
dtypes: bool(10), float64(11), int64(12), object(17)
memory usage: 519.0+ KB

In [5]:
total_distance = df.distance.sum()
total_distance

np.float64(6442449.6)

In [6]:
dist_by_sport_type = df.groupby(by='sport_type').distance.sum()
dist_by_sport_type

sport_type
EBikeRide         90493.4
Elliptical        37256.5
Run             5347341.3
StairStepper      30175.4
Walk             926722.5
Workout           10460.5
Name: distance, dtype: float64

In [7]:
for cat, dist in dist_by_sport_type.items():
    print(f'Percentage of total distance in category {cat}: {dist*100 / total_distance}%')

Percentage of total distance in category EBikeRide: 1.4046427309264478%
Percentage of total distance in category Elliptical: 0.5782971123282051%
Percentage of total distance in category Run: 83.00167842989413%
Percentage of total distance in category StairStepper: 0.4683839513467052%
Percentage of total distance in category Walk: 14.38462941176909%
Percentage of total distance in category Workout: 0.1623683637354338%

In [12]:
df.loc[df.distance.idxmax()]

resource_state                                                                   2
athlete                                     {'id': 120371207, 'resource_state': 1}
name                                                                      Walk 232
distance                                                                   21870.7
moving_time                                                                  17316
elapsed_time                                                                 32766
total_elevation_gain                                                         118.3
type                                                                          Walk
sport_type                                                                    Walk
id                                                                     13931305631
start_date                                                    2025-03-19T13:46:40Z
start_date_local                                              2025-03-19T09:46:40Z
timezone                                              (GMT-05:00) America/New_York
utc_offset                                                                  -14400
location_city                                                                 None
location_state                                                                None
location_country                                                              None
achievement_count                                                                0
kudos_count                                                                     13
comment_count                                                                    0
athlete_count                                                                    1
photo_count                                                                      0
map                              {'id': 'a13931305631', 'summary_polyline': 'ah...
trainer                                                                      False
commute                                                                      False
manual                                                                       False
private                                                                      False
visibility                                                          followers_only
flagged                                                                      False
gear_id                                                                  g17343209
start_latlng                                                [40.751537, -73.99419]
end_latlng                                                   [40.75068, -73.99172]
average_speed                                                                1.263
max_speed                                                                   13.196
average_cadence                                                              110.0
has_heartrate                                                                 True
average_heartrate                                                            105.0
max_heartrate                                                                142.0
heartrate_opt_out                                                            False
display_hide_heartrate_option                                                 True
elev_high                                                                     40.6
elev_low                                                                      11.1
upload_id                                                            14870307033.0
upload_id_str                                                          14870307033
external_id                        shealth14ada840-93c0-4a0b-b74c-a151ac8fb018.tcx
from_accepted_tag                                                            False
pr_count                                                                         0
total_photo_count                                                                0
has_kudoed                                                                   False
workout_type                                                                   NaN
Name: 104, dtype: object

In [13]:
df.loc[df.moving_time.idxmax()]

resource_state                                                                   2
athlete                                     {'id': 120371207, 'resource_state': 1}
name                                                                      Walk 232
distance                                                                   21870.7
moving_time                                                                  17316
elapsed_time                                                                 32766
total_elevation_gain                                                         118.3
type                                                                          Walk
sport_type                                                                    Walk
id                                                                     13931305631
start_date                                                    2025-03-19T13:46:40Z
start_date_local                                              2025-03-19T09:46:40Z
timezone                                              (GMT-05:00) America/New_York
utc_offset                                                                  -14400
location_city                                                                 None
location_state                                                                None
location_country                                                              None
achievement_count                                                                0
kudos_count                                                                     13
comment_count                                                                    0
athlete_count                                                                    1
photo_count                                                                      0
map                              {'id': 'a13931305631', 'summary_polyline': 'ah...
trainer                                                                      False
commute                                                                      False
manual                                                                       False
private                                                                      False
visibility                                                          followers_only
flagged                                                                      False
gear_id                                                                  g17343209
start_latlng                                                [40.751537, -73.99419]
end_latlng                                                   [40.75068, -73.99172]
average_speed                                                                1.263
max_speed                                                                   13.196
average_cadence                                                              110.0
has_heartrate                                                                 True
average_heartrate                                                            105.0
max_heartrate                                                                142.0
heartrate_opt_out                                                            False
display_hide_heartrate_option                                                 True
elev_high                                                                     40.6
elev_low                                                                      11.1
upload_id                                                            14870307033.0
upload_id_str                                                          14870307033
external_id                        shealth14ada840-93c0-4a0b-b74c-a151ac8fb018.tcx
from_accepted_tag                                                            False
pr_count                                                                         0
total_photo_count                                                                0
has_kudoed                                                                   False
workout_type                                                                   NaN
Name: 104, dtype: object